<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Core_model extends CI_Model
{

    
    function __construct()
    {
        parent::__construct();
        // $this->db = $this->load->database('default', TRUE);
        $this->db2 = $this->load->database('core', TRUE);
    }


    function getDataCR006Core($minggu1,$minggu2){
        $sql_query = $this->db2->query('call obox_CR006("'.$minggu1.'","'.$minggu2.'")');

        mysqli_next_result( $this->db2->conn_id);
        if($sql_query->num_rows()>0){
            return $sql_query->result_array();
        }    
    }

    function getDataCR007Core($minggu2){
        return "";
    }

    function getDataCR008Core($minggu1,$minggu2){
        $sql_query = $this->db2->query('call obox_CR008("'.$minggu1.'","'.$minggu2.'")');
		
        mysqli_next_result( $this->db2->conn_id);
        if($sql_query->num_rows()>0){
            return $sql_query->result_array();
        }    
    }


    function getDataCR009Core($minggu1,$minggu2){
        $sql_query = $this->db2->query('call obox_CR009("'.$minggu1.'","'.$minggu2.'")');
		
        mysqli_next_result( $this->db2->conn_id);
        if($sql_query->num_rows()>0){
            return $sql_query->result_array();
        }    
    }

    function getDataOP001Core($minggu1,$minggu2){
        $sql_query = $this->db2->query('call obox_OP001("'.$minggu1.'","'.$minggu2.'")');

        mysqli_next_result( $this->db2->conn_id);
        if($sql_query->num_rows()>0){
            return $sql_query->result_array();
        }    
    }

    function getDataOP002Core($minggu1,$minggu2){
		
        $sql_query = $this->db2->query('call obox_OP002("'.$minggu1.'","'.$minggu2.'")');
		
        mysqli_next_result( $this->db2->conn_id);
        if($sql_query->num_rows()>0){
            return $sql_query->result_array();
        }    
    }

    function getDataLQ003Core($minggu1,$minggu2){
        $sql_query = $this->db2->query('call obox_LQ003("'.$minggu1.'","'.$minggu2.'")');

        mysqli_next_result( $this->db2->conn_id);
        if($sql_query->num_rows()>0){
            return $sql_query->result_array();
        }    
    }

    function getDataLQ004Core($minggu1,$minggu2){
        $sql_query = $this->db2->query('call obox_LQ004("'.$minggu1.'","'.$minggu2.'")');

        mysqli_next_result( $this->db2->conn_id);
        if($sql_query->num_rows()>0){
            return $sql_query->result_array();
        }    
    }
    

    function getDataLQ005Core($minggu2){
        $sql_query = $this->db2->query('call obox_LQ005("'.$minggu2.'")');

        mysqli_next_result( $this->db2->conn_id);
        if($sql_query->num_rows()>0){
            return $sql_query->result_array();
        }    
    }

    function getDataLQ006Core($minggu2){
        $sql_query = $this->db2->query('call obox_LQ006("'.$minggu2.'")');

        mysqli_next_result( $this->db2->conn_id);
        if($sql_query->num_rows()>0){
            return $sql_query->result_array();
        }    
    }

    function getChangeDateCollectibility($norekening,$minggu1,$minggu2){
        $sql_query = $this->db2->query('call obox_getTanggalKolektibilitas("'.$norekening.'","'.$minggu1.'","'.$minggu2.'")');
        
        mysqli_next_result( $this->db2->conn_id);
        if($sql_query->num_rows()>0){
            return $sql_query->result_array();
        }    
    }

    function getDataPerubahanKolek($minggu1,$minggu2){
        $sql_query = $this->db2->query('call obox_CR009("'.$minggu1.'","'.$minggu2.'")');

        mysqli_next_result( $this->db2->conn_id);
        if($sql_query->num_rows()>0){
            return $sql_query->result_array();
        }    
    }

}

/* End of file Antrian_model.php */
/* Location: ./application/models/Antrian_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-03-05 13:10:59 */
/* http://harviacode.com */